import { useState } from "react";
import DashboardLayout from "@/components/dashboard/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Link2,
  Copy,
  ExternalLink,
  CheckCircle,
  Clock,
  Users,
  Search,
} from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { format } from "date-fns";

const RegistrationLinks = () => {
  const { schoolId } = useAuth();
  const { toast } = useToast();
  const [searchQuery, setSearchQuery] = useState("");

  const { data: tokens, isLoading } = useQuery({
    queryKey: ["school-reg-tokens", schoolId],
    queryFn: async () => {
      if (!schoolId) return [];
      const { data, error } = await supabase
        .from("student_registration_tokens")
        .select("*")
        .eq("school_id", schoolId)
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data || [];
    },
    enabled: !!schoolId,
  });

  const registrationUrl = schoolId
    ? `${window.location.origin}/student-registration?school=${schoolId}`
    : "";

  const copyLink = (token: string) => {
    const fullLink = `${registrationUrl}&pin=${token}`;
    navigator.clipboard.writeText(fullLink);
    toast({ title: "Link copied!", description: "Share this link with the student" });
  };

  const copyBaseLink = () => {
    navigator.clipboard.writeText(registrationUrl);
    toast({ title: "Base link copied!", description: "Students will need a PIN to access the form" });
  };

  const filteredTokens = tokens?.filter((t) => {
    if (!searchQuery) return true;
    const q = searchQuery.toLowerCase();
    return t.token.toLowerCase().includes(q) || t.used_by_name?.toLowerCase().includes(q);
  });

  const totalTokens = tokens?.length || 0;
  const usedTokens = tokens?.filter((t) => t.is_used).length || 0;
  const unusedTokens = totalTokens - usedTokens;

  return (
    <DashboardLayout role="school-admin">
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
            <Link2 className="w-6 h-6" /> Student Registration Links
          </h1>
          <p className="text-muted-foreground">
            Share registration links with new students. Each student needs a PIN to register.
          </p>
        </div>

        {/* Registration URL */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <ExternalLink className="w-5 h-5" /> Registration Page
            </CardTitle>
            <CardDescription>
              This is your school's student registration URL. Share it along with a registration PIN.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex gap-2">
              <Input value={registrationUrl} readOnly className="font-mono text-sm" />
              <Button variant="outline" onClick={copyBaseLink}>
                <Copy className="w-4 h-4 mr-2" /> Copy
              </Button>
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              Registration PINs are generated by the platform administrator. Contact them to get PINs for new intake.
            </p>
          </CardContent>
        </Card>

        {/* Stats */}
        <div className="grid grid-cols-3 gap-4">
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                  <Users className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <p className="text-2xl font-bold text-foreground">{totalTokens}</p>
                  <p className="text-xs text-muted-foreground">Total PINs</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-success/10 flex items-center justify-center">
                  <Clock className="w-5 h-5 text-success" />
                </div>
                <div>
                  <p className="text-2xl font-bold text-foreground">{unusedTokens}</p>
                  <p className="text-xs text-muted-foreground">Available</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-warning/10 flex items-center justify-center">
                  <CheckCircle className="w-5 h-5 text-warning" />
                </div>
                <div>
                  <p className="text-2xl font-bold text-foreground">{usedTokens}</p>
                  <p className="text-xs text-muted-foreground">Used</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Tokens list */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Registration PINs ({filteredTokens?.length || 0})</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="mb-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input placeholder="Search PIN or student name..." className="pl-10" value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} />
              </div>
            </div>
            {isLoading ? (
              <div className="flex justify-center py-12">
                <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-primary" />
              </div>
            ) : filteredTokens?.length === 0 ? (
              <div className="text-center py-12 text-muted-foreground">
                <Users className="w-12 h-12 mx-auto mb-3 opacity-50" />
                <p>No registration PINs available</p>
                <p className="text-sm">Contact the platform administrator to generate PINs for your school</p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>PIN</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Used By</TableHead>
                      <TableHead>Date</TableHead>
                      <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredTokens?.map((token) => (
                      <TableRow key={token.id}>
                        <TableCell>
                          <code className="text-sm font-mono bg-muted px-2 py-1 rounded">{token.token}</code>
                        </TableCell>
                        <TableCell>
                          {token.is_used ? (
                            <Badge variant="outline" className="bg-success/10 text-success border-success/30">
                              <CheckCircle className="w-3 h-3 mr-1" /> Used
                            </Badge>
                          ) : (
                            <Badge variant="outline" className="bg-warning/10 text-warning border-warning/30">
                              <Clock className="w-3 h-3 mr-1" /> Available
                            </Badge>
                          )}
                        </TableCell>
                        <TableCell className="text-sm text-muted-foreground">{token.used_by_name || "—"}</TableCell>
                        <TableCell className="text-sm text-muted-foreground">
                          {token.created_at ? format(new Date(token.created_at), "dd MMM yyyy") : "—"}
                        </TableCell>
                        <TableCell className="text-right">
                          {!token.is_used && (
                            <Button variant="ghost" size="sm" onClick={() => copyLink(token.token)}>
                              <Copy className="w-4 h-4 mr-1" /> Copy Link
                            </Button>
                          )}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
};

export default RegistrationLinks;
