
-- First create Biology subject
INSERT INTO subjects (school_id, name, code, category, is_islamic, is_vocational)
VALUES ('1db1c085-c9c3-483e-941d-ea3b3f508bc7', 'Biology', 'BIO', 'science', false, false);

-- Now insert JAMB Biology past questions
INSERT INTO exam_questions (school_id, subject_id, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, explanation)
SELECT 
  '1db1c085-c9c3-483e-941d-ea3b3f508bc7',
  s.id,
  q.question_text,
  q.option_a,
  q.option_b,
  q.option_c,
  q.option_d,
  q.correct_option,
  q.difficulty,
  q.explanation
FROM subjects s,
(VALUES
  ('Which of the following elements are necessary for the formation of chlorophyll in a plant?', 'Magnesium and iron', 'Calcium and potassium', 'Calcium and sulphur', 'Potassium and sulphur', 'A', 'medium', 'Magnesium is a central atom in chlorophyll molecules, and iron is needed as a cofactor.'),
  ('Which of the following statements is NOT true of mammalian erythrocytes?', 'They have haemoglobin', 'They appear yellow when looked at singly', 'They are disc-shaped', 'They have nuclei at maturity', 'D', 'medium', 'Mature mammalian red blood cells lack nuclei.'),
  ('In woody plants, gases and water vapour are transported across the stems by the', 'xylem fibres', 'medullary fibres', 'medullary rays', 'phloem fibres', 'C', 'medium', 'Medullary rays facilitate lateral transport of gases and water vapour.'),
  ('In a dicot leaf, guard cells differ from other epidermal cells because they', 'have no definite shape', 'lack nuclei', 'are smaller', 'contain chloroplasts', 'D', 'easy', 'Guard cells are unique among epidermal cells in containing chloroplasts.'),
  ('Herbs differ from shrubs because they', 'do not produce fruits', 'are useful to herbalists', 'do not become woody', 'are only annuals', 'C', 'easy', 'Herbs have soft, non-woody stems unlike shrubs.'),
  ('If an isolated living cell is left in distilled water for two hours, it is likely to', 'lose some of its water', 'lose all of its water', 'reproduce by binary fission', 'become more turgid', 'D', 'medium', 'Water moves into the cell by osmosis from the hypotonic distilled water.'),
  ('If an organic compound has its Hydrogen:Oxygen ratio as 2:1, it is likely to be', 'a protein', 'a carbohydrate', 'a fat', 'a fatty acid and glycerol', 'B', 'medium', 'Carbohydrates have the general formula Cx(H2O)y, giving a H:O ratio of 2:1.'),
  ('In the onion bulb, food is stored in the', 'stem', 'lateral buds', 'cotyledons', 'leaf bases', 'D', 'medium', 'Food in onion bulbs is stored in the fleshy leaf bases.'),
  ('What type of fruit is formed from a single flower having several free carpels?', 'Multiple fruit', 'Simple fruit', 'Aggregate fruit', 'Dehiscent fruit', 'C', 'medium', 'An aggregate fruit develops from a single flower with multiple free carpels.'),
  ('Which of the following diseases is NOT caused by a virus?', 'Rinderpest', 'Maize rust', 'Newcastle disease', 'Swine fever', 'B', 'medium', 'Maize rust is caused by a fungus, not a virus.'),
  ('A centipede differs from a millipede by its', 'colour', 'numerous abdominal segments', 'paired legs on each segment', 'poison claws', 'D', 'easy', 'Centipedes have poison claws which millipedes lack.'),
  ('An organism having one pair of identical genes is', 'a heterozygote', 'a hybrid', 'an allelomorph', 'a homozygote', 'D', 'easy', 'A homozygote has identical alleles for a particular gene.'),
  ('Plants which can survive in places where the water supply is limited are', 'bryophytes', 'mesophytes', 'xerophytes', 'hydrophytes', 'C', 'easy', 'Xerophytes are adapted to survive in dry conditions.'),
  ('One disease NOT caused directly by bacteria is', 'malaria', 'tuberculosis', 'pneumonia', 'tetanus', 'A', 'easy', 'Malaria is caused by Plasmodium parasites.'),
  ('Which of these worms is beneficial to man?', 'Hookworm', 'Tapeworm', 'Roundworm', 'Earthworm', 'D', 'easy', 'Earthworms improve soil fertility.'),
  ('Starting from the skull end, the vertebrae are arranged in the order:', 'axis, atlas, cervical, thoracic, lumbar', 'atlas, cervical, axis, thoracic, lumbar', 'atlas, axis, thoracic, cervical, lumbar', 'atlas, axis, cervical, thoracic, lumbar', 'D', 'medium', 'The correct order from the skull is atlas, axis, cervical, thoracic, lumbar.'),
  ('Which disease could be exclusively associated with a river basin?', 'Malaria', 'Syphilis', 'Onchocerciasis', 'Cholera', 'C', 'medium', 'Onchocerciasis (river blindness) is transmitted by blackflies near rivers.'),
  ('Which of the following will NOT allow osmosis to take place?', 'Pig bladder', 'Cellophane', 'Parchment paper', 'Transparent polythene', 'D', 'medium', 'Polythene is not a semi-permeable membrane.'),
  ('The function of the ossicles in the mammalian ear is the', 'transmission of vibrations', 'regulation of pressures', 'support of the inner ear', 'maintenance of balance', 'A', 'easy', 'The ear ossicles transmit and amplify sound vibrations.'),
  ('Which instrument is used for determining turbidity of water?', 'Thermometer', 'Secchi Disc', 'Rain gauge', 'Hygrometer', 'B', 'easy', 'A Secchi disc measures water clarity/turbidity.'),
  ('The tuber of cassava is NOT a stem tuber because it', 'is distended with food reserve', 'has an aerial shoot portion', 'has structures called roots', 'lacks axillary buds', 'D', 'medium', 'Cassava tuber is a root tuber; it lacks axillary buds.'),
  ('The mouth parts of the housefly are adapted for', 'lapping and sponging', 'sucking and chewing', 'piercing and sucking', 'chewing and lapping', 'A', 'easy', 'Housefly mouthparts are adapted for lapping and sponging.'),
  ('The male toad differs from the female by having', 'vocal sacs', 'shorter hind limbs', 'longer fore limbs', 'bulging eyes', 'A', 'easy', 'Male toads have vocal sacs for calling during mating.'),
  ('Mosses, liverworts and ferns can be grouped together because they', 'are all aquatic plants', 'all grow in deserts', 'are seedless plants', 'have undifferentiated bodies', 'C', 'medium', 'They all reproduce via spores, not seeds.'),
  ('Which invertebrate does NOT possess antennae?', 'Centipede', 'Crustacean', 'Millipede', 'Spider', 'D', 'easy', 'Spiders are arachnids and lack antennae.'),
  ('Which cell constituent is NOT common in both plants and animals?', 'Mitochondria', 'Chloroplasts', 'Ribosomes', 'Golgi apparatus', 'B', 'easy', 'Chloroplasts are only found in plant cells.'),
  ('The character-producing factors in living organisms are', 'chromomeres', 'alleles', 'chromatids', 'genes', 'D', 'easy', 'Genes determine characteristics in organisms.'),
  ('The mammalian organ through which nourishment diffuses into a developing embryo is', 'amnion', 'chorion', 'umbilical cord', 'placenta', 'D', 'easy', 'The placenta facilitates nutrient and gas exchange.'),
  ('In Rhizopus, carbohydrate is stored in the form of', 'glucose', 'paramylon', 'glycogen', 'starch', 'C', 'medium', 'Fungi store carbohydrate as glycogen.'),
  ('Which statement about transpiration rate is INCORRECT?', 'It depends on temperature', 'It is affected by light intensity', 'It is unaffected by humidity', 'It depends on air movement', 'C', 'medium', 'Humidity does affect transpiration rate.'),
  ('When a Spirogyra cell is in a concentrated salt solution, it', 'remains unchanged', 'takes up water and bursts', 'absorbs a little water', 'loses water and shrivels', 'D', 'medium', 'In a hypertonic solution, water leaves the cell by osmosis.'),
  ('On what structures are the units of inheritance situated?', 'Golgi bodies', 'Ribosomes', 'Chromosomes', 'Endoplasmic reticulum', 'C', 'easy', 'Genes are located on chromosomes.'),
  ('Production of naked seeds is a feature of plants called', 'grasses', 'conifers', 'legumes', 'palms', 'B', 'easy', 'Conifers (gymnosperms) produce naked seeds.'),
  ('The theory of natural selection was developed by', 'Lamarck and Darwin', 'Darwin and Wallace', 'Wallace and Mendel', 'Mendel and Lamarck', 'B', 'easy', 'Darwin and Wallace developed the theory of natural selection.'),
  ('Which enzymes are in pancreatic juice?', 'Ptyalin, lipase, pepsin', 'Maltase, erepsin, trypsin', 'Rennin, sucrase, lipase', 'Amylase, lipase, trypsin', 'D', 'medium', 'Pancreatic juice contains amylase, lipase, and trypsin.'),
  ('Double fertilization in higher plants ensures the', 'formation of a fertile embryo', 'formation of embryo and endosperm', 'development of the seed', 'development of the fruit', 'B', 'medium', 'Double fertilization produces both embryo and endosperm.'),
  ('The function of the yolk in mammalian development is to', 'supply nutrients to the embryo', 'act as shock-absorber', 'supply air to the embryo', 'facilitate excretion', 'A', 'easy', 'The yolk provides nutrients to the developing embryo.'),
  ('Fruits which develop without fertilization are', 'false', 'multiple', 'aggregate', 'parthenocarpic', 'D', 'medium', 'Parthenocarpic fruits develop without fertilization.'),
  ('Soil with the finest particles is called', 'silt', 'clay', 'sand', 'gravel', 'B', 'easy', 'Clay has the finest soil particles.'),
  ('Neurons that receive stimuli from the body are called', 'sensory neurons', 'efferent neurons', 'motor neurons', 'relay neurons', 'A', 'easy', 'Sensory neurons receive stimuli from receptors.'),
  ('A population is a collection of similar organisms that', 'behave the same way', 'interbreed freely', 'live in the same habitat', 'eat the same food', 'B', 'medium', 'A population consists of organisms that can interbreed.'),
  ('The hereditary material of the cell is', 'RNA', 'protein', 'DNA', 'carbohydrate', 'C', 'easy', 'DNA carries genetic information.'),
  ('Homologous chromosomes separate during', 'meiosis', 'cytolysis', 'mitosis', 'cleavage', 'A', 'easy', 'Homologous chromosomes separate during meiosis I.'),
  ('An example of a caryopsis is', 'coconut', 'tomato', 'guava', 'maize grain', 'D', 'medium', 'Maize grain is a caryopsis where pericarp fuses with seed coat.'),
  ('A limiting factor near a chemical factory is likely', 'humidity', 'pH', 'wind', 'light', 'B', 'medium', 'Chemical factories release pollutants that alter pH.'),
  ('The pioneer organisms in ecological succession are', 'lichens', 'algae', 'ferns', 'mosses', 'A', 'easy', 'Lichens are first colonizers on bare rock.'),
  ('Mycorrhiza is an association between fungi and', 'roots of higher plants', 'filamentous algae', 'bacteria', 'protozoans', 'A', 'easy', 'Mycorrhiza is a symbiotic relationship between fungi and plant roots.'),
  ('A density-dependent factor regulating population is', 'sudden flood', 'disease', 'fire outbreak', 'drought', 'B', 'medium', 'Disease spreads more in dense populations.'),
  ('Sunken stomata and folded leaves are adaptations to', 'prevent pathogen entry', 'prevent guttation', 'remove excess water', 'reduce water loss', 'D', 'easy', 'These features reduce transpiration in xerophytes.'),
  ('Spines and shells on animals are adaptations for', 'physical defence', 'camouflage', 'chemical defence', 'mimicry', 'A', 'easy', 'Spines and shells provide physical protection.'),
  ('The most effective method for non-biodegradable pollution is', 'burying', 'dumping', 'incineration', 'recycling', 'D', 'easy', 'Recycling is the most sustainable method.'),
  ('One example of fossil fuels is', 'coral', 'limestone', 'firewood', 'coal', 'D', 'easy', 'Coal is a fossil fuel from ancient plant material.'),
  ('The organism extensively used to test chromosome theory of heredity is', 'Homo sapiens', 'Drosophila melanogaster', 'Zea mays', 'Musca domestica', 'B', 'medium', 'Drosophila melanogaster is the classic model organism for genetics.'),
  ('An example of cryptic colouration is the', 'bright marks on a poisonous frog', 'bright colour of a flower', 'mottled colours on moths on lichens', 'green colour of a plant', 'C', 'medium', 'Cryptic colouration helps organisms blend with their environment.'),
  ('An argument against Lamarck theory of evolution is that', 'acquired traits cannot be inherited', 'disuse cannot weaken body parts', 'disused parts drop off in offspring', 'traits cannot be acquired through use', 'A', 'medium', 'Acquired characteristics are not inherited.'),
  ('The best method of propagating sugarcane is by', 'stem cuttings', 'seed sowing', 'layering', 'grafting', 'A', 'easy', 'Sugarcane is propagated through stem cuttings.'),
  ('Plant response to stimuli in a non-directional manner is', 'nastic movement', 'phototropism', 'tactic movement', 'geotropism', 'A', 'medium', 'Nastic movements are non-directional responses to stimuli.')
) AS q(question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, explanation)
WHERE s.name = 'Biology' AND s.school_id = '1db1c085-c9c3-483e-941d-ea3b3f508bc7';
